### ISSUE TITLE
Talk Proposal: Magrathea

### ISSUE THREAD

**Issue by DavidRRice** [vast-seminars/talk-proposals#21]
### Name of software library or topic
Magrathea

### URL to software repository
https://github.com/Huang-CL/Magrathea

### Name of person who will give the talk
David R. Rice

### Brief abstract
The community uses a variety of models to characterize the interior structure of small planets. Underlying these models are multiple computational techniques, numerous experimental measurements and theoretical estimates of the equations of state for planet-building materials, and differing treatments of temperature. MAGRATHEA is an open-source interior structure solver which can be customized to user-defined planet models. Our code features adaptable phase diagrams for the core, mantle, hydrosphere, and atmosphere and transparent storage for equations of state. I will demonstrate how the community can use and contribute to the code.

I should be available on all dates this fall.

**Comment by jrenaud90** [comment]
Hey @DavidRRice - We would love to have you kick off our first exoVAST on Sept. 20th if you are still available and interested. Since this is our first exoVAST, and since the time slot is only an hour for two speakers, we would like to have the first talk come from the EMAC/exoVAST team to introduce the series and EMAC. Then you would be up next as the first "real" exoVAST speaker to discuss Magrathea and your work (talk would be approx 20 minutes to allow time for questions and discussion). The session will be held virtually on zoom starting at 11:00 AM (US Eastern Time) on Sept 20th. 

If that plan sounds good to you just confirm with me here and if you could share a talk title that we can use to advertise the event. Thank you so much for your interest, looking forward to it!

**Comment by jrenaud90** [comment]
Talk given on Sept. 20th, 2023!

**Comment by jrenaud90** [comment]
Hey @DavidRRice - The recording is now live! https://youtu.be/gVZpt-_U724

**Comment by DavidRRice** [comment]
Awesome sauce!
