### ISSUE TITLE
Talk Proposal: WHFast512

### ISSUE THREAD

**Issue by hannorein** [vast-seminars/talk-proposals#23]
### Name of software library or topic
WHFast512 (part of REBOUND)

### URL to software repository
https://github.com/hannorein/rebound

### Name of person who will give the talk
Hanno Rein (University of Toronto)

### Brief abstract
N-body simulation with a small number of particles are difficult to parallelizable using GPUs or CPU clusters because communication overhead often dominate. As a result long term integrations can take weeks or even months to run on modern CPUs. In this talk, I will present the new symplectic N-body integrator WHFast512 which is using Single Instruction Multiple Data (SIMD) parallelism and 512-bit Advanced Vector Extensions (AVX512). We were able to speed up integrations of planetary systems by up to 4.7x compared to the non-vectorized version of WHFast. WHFast512 can integrate the Solar System with 8 planets for 5 billion years in a single day. To our knowledge, this makes WHFast512 by far the fastest direct N-body integrator for systems of this kind. In this talk I will not only present WHFast512 but also give a short introduction on how to write programs using these AVX512 instructions so that you can optimize your own code as well.

**Comment by jrenaud90** [comment]
Hi, @hannorein!
   Thank you for your submission. We would love to have you speak at an upcoming exoVAST talk. We currently have 1 spot available on either November 1st and December 6th (both at 11am US Eastern). If you are available for one/both of those dates please let me know in a reply here. 
 
A note about the format: Your talk will be one of two 20 minute talks with time for questions afterwards. One of the goals of exoVAST is to create a new series of tutorial/informational videos for tools hosted on [EMAC](https://emac.gsfc.nasa.gov/?q=WHfast) that may not already have one. We plan to upload these talks to YouTube and link them to your resource on EMAC so that potential users can get an introduction. I know 20 minutes is not enough time to give a comprehensive tutorial on your resource, but if possible: we are recommending ~half the talk dedicated to the science / history (likely similar to a talk you have given in the past) and the other ~half a small demonstration of your resource. This could just be how to run one small aspect of it, how to install it, anything that you think may, 1) help other scientists be able to use your tool and/or 2) get them excited to check it out. I know live demos can be fraught with problems, so you are welcome to simply have images on a slide show walking through a demo rather than actually running any code.
 
I know this is a non-traditional format so I would be happy to talk to you more about it! If you are game, then I just need the information found at the end of this message (and which dates you could speak on).
 
Thank you,
Joe
 
~_exoVAST Speaker Form_
Speaker Name and Affiliation:
Speaker Pronouns:
Short Speaker Bio:
Talk Title:
You are okay with the talk being recorded and uploaded to the VAST/EMAC YouTube:
~

**Comment by hannorein** [comment]
Thank you. November 1st would be great. 

Speaker Name and Affiliation: Hanno Rein (University of Toronto)
Speaker Pronouns: he/him
Short Speaker Bio: Hanno Rein received his PhD from the University of Cambridge under the supervision of John Papaloizou in 2010. He was a post-doctoral fellow at the Institute of Advanced Study in Princeton from 2010 to 2013. Since then he has been a Professor at the University of Toronto. 
Talk Title: Accelerating a single N-body simulation with 8 particles using AVX512 instructions
You are okay with the talk being recorded and uploaded to the VAST/EMAC YouTube: Yes.

**Comment by jrenaud90** [comment]
Awesome! Thanks for the fast reply. I will send you a message with a reminder and the Zoom information about ~a week before.

Scheduled for Nov. 1st (11am US Eastern), 2023.

**Comment by jrenaud90** [comment]
Hi, @hannorein  – Just checking in to see if you are still good to go for your exoVAST talk next Wednesday, Nov 1st at 11am US Eastern.

The zoom room will be: [https://us02web.zoom.us/j/85176586228?pwd=a3lpTDIrTmRmOWxQQ0hNUFBSeDEvZz09](https://us02web.zoom.us/j/85176586228?pwd=a3lpTDIrTmRmOWxQQ0hNUFBSeDEvZz09)

And a reminder of the format: 

The Virtual Astronomy Software Talks (VAST) is a monthly virtual seminar series on astronomy-related software and topics. Each month features two 20-minute talks followed by an open discussion. The goal of these talks is to connect astronomers and physicists to developers that are creating awesome astronomy software and databases.
 
exoVAST is a new series that is built off of the VAST model but focused on software specific to exoplanet science. It will be co-hosted by the VAST and EMAC teams. We want these talks to be a quick introduction to resources featured on EMAC so that other users can quickly learn how to use (and why they should) these tools. In that spirit, we are hoping that ~50% of your talk will be either a live demo or just a walk through with pictures/code of how someone can tackle a simple task. We know that 10 minutes is not nearly enough time to really show case the power of your software, but we hope it can at least show enough to motivate others to learn more. Ideally, we would like these talks to be recorded and uploaded to YouTube for later viewing. I would be happy to discuss the format of the talk more if you are interested.

Thank you so much!
Joe

**Comment by hannorein** [comment]
Yes.

**Comment by jrenaud90** [comment]
Hi, @hannorein - Looking forward to your talk today in about 30 minutes! If you'd like to hop on a few minutes early to test out slides/visuals, please feel free. connection link is: https://us02web.zoom.us/j/85176586228?pwd=a3lpTDIrTmRmOWxQQ0hNUFBSeDEvZz09

**Comment by hannorein** [comment]
Will the recording be shared online?

**Comment by zingale** [comment]
yes.  It will be put on youtube shortly, likely the one hosted by EMAC

**Comment by jrenaud90** [comment]
Hi, @hannorein - The recording is now live! https://youtu.be/xaC51s25T70

**Comment by hannorein** [comment]
Cool. Thanks!
